### ISSUE TITLE
Browser-sync serves before build is complete

### ISSUE THREAD

**Issue by joshosbrn** [tinychime/jekyons#9]
This only seems to be an issue when starting with a fresh Jekyons clone, but browser-sync seems to serve the site a few seconds before it's actually done building resulting in a 'Cannot GET /' error at localhost. A few seconds later, it finishes building but you then have to manually reload the browser to preview changes. If you kill gulp and re-run, it works as expected.

You should be able to reproduce by cloning a new Jekyons project, installing dependencies and running 'gulp'.

**Comment by alexcarpenter** [comment]
hmm, might suggest updating the docs to include a command to build the `_site` files once, then run `gulp` to keep from having to install another dependancy.

Otherwise you could make use of [gulp-sequence](https://www.npmjs.com/package/gulp-sequence) to run the tasks in a specific order.

**Comment by joshosbrn** [comment]
I've been using your first solution on setup and that works just fine for now. I may explore gulp-sequence in the future. Updating the docs. Thanks!
